package:
  name: probfit

source:
  git_tag: master
  git_url: https://github.com/mhedges/probfit.git

build:
  number: 1

requirements:
  build:
    - numpy
    - python
    - setuptools
    - iminuit
