package:
  name: probfit
  version: 1.0.5

source:
  git_url: https://github.com/iminuit/probfit.git

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy
